#!/bin/sh

. gconfig

TUSER=ubuntu
QUIET_FLAG=

usage() {
  echo "Usage: ${0##*/} [OPTION]... <command>"
  echo "Run command on build target."
  echo
  cat << EOF
  --help    display this help and exit
  --user=U  run as U instead of ubuntu
EOF
}

if [ $# != 0 ] ; then
  while true ; do
    case "$1" in
      --help|-h)
        usage
        exit 0
        ;;
      --user|-u)
        TUSER="$2"
        shift 2
        ;;
      --quiet|-q)
        QUIET_FLAG="-q"
        shift 1
        ;;
      --*)
        echo "unrecognized option $1"
        exit 1
        ;;
      *)
        break
        ;;
    esac
  done
fi

if [ $# = 0 ] ; then
  usage
  exit 1
fi

if [ -z "$USE_LXC" ]; then
    scp $QUIET_FLAG -r -oConnectTimeout=30 -oNoHostAuthenticationForLocalhost=yes -i ${GITIAN_BASE:-.}/var/id_dsa -P $VM_SSH_PORT $1 $TUSER@localhost:$2
else
    config-lxc
    tar -C `dirname "$1"` -cf - `basename "$1"` | sudo lxc-start -n gitian -f var/lxc.config -- sudo -i -u $TUSER tar -C "$2" -xf -
fi
